language: c

arch:
  - amd64
  - arm64

os: linux

addons:
  apt:
    packages:
    - libmosquitto-dev
    - libconfig-dev

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build

script: cmake -DCMAKE_C_FLAGS='-Wall -Wextra -Wcast-align' .. && make
