language: c

arch:
  - amd64
  - arm64

os: linux

addons:
  apt:
    packages:
    - libmosquitto-dev
    - libconfig-dev
    - libcmocka-dev 

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build

script: cmake -DCMAKE_C_FLAGS='-Wall -Wextra -Wcast-align' -DMQTTA_WITH_TESTS=ON .. && make
